### ISSUE TITLE
no difference in mismatch files

### ISSUE THREAD

**Issue by ramestica** [fourier/ztree#29] opened 2015-09-22 16:25 UTC
Hi,

all files are marked as different (red). For a moment I though that it was some highlighting issue in my configuration, but if I try to customize one of the file names in red (which I know are otherwise identical files) then I get ztreep-diff-model-diff-face, which I suppose it really means that ztree thinks those two files are different.

My problem is so basic that it should be something wrong in my configuration. Any hint for anything I should be looking for? 

Thanks,
 Rodrigo

**Comment by fourier** [comment] 2015-09-22 16:40
Can you try to run emacs -q, load ztree and run the ztree-diff again with the same directories?

**Comment by ramestica** [comment] 2015-09-23 16:58
while testing 'emacs -q' it dawned in my mind that perhaps the problem happens to me only on remote directories accessed through tramp. And sure enough, with -q or with my own emacs configuration files are all marked as different when they are located in remote directories. On local directories only files that differ are marked a so.

So, it must be something related to comparing the files through tramp.

**Comment by fourier** [comment] 2015-09-23 17:08
Yes, I've never tested with TRAMP neither it was my aim. @Silex reported what the TRAMP works and even suggested a patch for it. Personally I don't know how could it work since the main 'backend' of the ztree-diff is a simple *diff* command.

**Comment by Silex** [comment] 2016-08-09 13:36
Oops. Sorry I somehow missed the @Silex mention, you're right it seems to bug when diffing remote files (all files are marked as different). I'll see what I can do.

**Comment by Silex** [comment] 2016-08-09 13:53
Ok, the problem is because of https://github.com/fourier/ztree/commit/32db847e4545483bdb08d6facdb8bb9887fb6d6d

I'm making a PR to correct it.

**Comment by Silex** [comment] 2016-08-14 13:37
@ramestica: please test the PR fixes it for you.

**Comment by Silex** [comment] 2016-08-14 13:38
@fourier: for your information, the diff command runs over TRAMP too, that's why it works.

**Comment by ramestica** [comment] 2016-08-25 22:08
the PR fixes the problem. 

Many thanks

**Closed** 2016-09-23 05:58 UTC
